version: "3"
services:
  client:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.vite
    ports:
      - 5173:80

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile.express
    ports:
      - 3001:3001
    environment:
      - HOST=http://localhost
