name: Build and push images

env:
  GITHUB_SHA: ${{github.sha}}
on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push API image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./api
          file: ./api/Dockerfile.express
          push: true
          tags: |
            samjamesjazz/my-hms-api:latest
            samjamesjazz/my-hms-api:${{ env.GITHUB_SHA }}
          labels: ${{ steps.meta.outputs.labels }}
